language: node_js
cache:
    directories: [~./npm]
notifications:
    email: false
node_js: v10.0.0
before_install:
    - nvm install
    - npm prune
    - npm install
script:
    - npm run build
    - npm run test
    - npm run tslint
after_success:

branches:
    except: [/^v\d+\.\d+\.\d+$/]
